module.exports = [
  // Original roster
  { name: 'Max Tani', publication: 'Semafor' },
  { name: 'Theodore Schleifer', publication: 'New York Times' },
  { name: 'Taylor Lorenz', publication: 'UserMag' },
  { name: 'Shane Goldmacher', publication: 'New York Times' },
  { name: 'Alex Thompson', publication: 'Axios' },
  { name: 'Sara Fischer', publication: 'Axios' },
  { name: 'Ryan Broderick', publication: 'Garbage Day' },
  { name: 'Oliver Darcy', publication: 'Status' },
  { name: 'Peter Hamby', publication: 'Puck' },
  { name: 'Jessica Testa', publication: 'New York Times' },
  // Added round 2
  { name: 'Dave Weigel', publication: 'Semafor' },
  { name: 'Jonathan Martin', publication: 'POLITICO' },
  { name: 'Lauren Egan', publication: 'The Bulwark' },
  { name: 'Will Sommer', publication: 'The Bulwark' },
  { name: 'Sam Stein', publication: 'The Bulwark' },
  { name: 'Issie Lapowsky', publication: 'Freelance' },
  { name: 'Zach Montellaro', publication: 'POLITICO' },
  { name: 'Ben Smith', publication: 'Semafor' },
  { name: 'Jessica Piper', publication: 'POLITICO' },
  { name: 'Elena Schneider', publication: 'NOTUS' },
  { name: 'Nancy Scola', publication: 'Freelance' },
  { name: 'Adam Wren', publication: 'POLITICO' },
  { name: 'Michael Scherer', publication: 'Washington Post' },
  // Added round 3
  { name: 'Alex Roarty', publication: 'Freelance' },
  { name: 'Joshua Green', publication: 'Bloomberg' },
  { name: 'Gabriel Debenedetti', publication: 'New York Magazine' },
  { name: 'Edward-Isaac Dovere', publication: 'The Atlantic' },
  { name: 'Nate Silver', publication: 'Silver Bulletin' },
  { name: 'Joseph Bernstein', publication: 'New York Times' },
];
